# Generated by Django 5.0 on 2023-12-23 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ratio', models.IntegerField()),
                ('settled', models.BooleanField(default=False)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('is_owed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_owed', to=settings.AUTH_USER_MODEL)),
                ('owes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
