# Generated by Django 5.0 on 2023-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
