# Generated by Django 5.0 on 2023-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_bill', '0002_alter_debt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
