# Generated by Django 5.0 on 2023-12-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_bill', '0004_alter_debt_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='owes',
            new_name='owner',
        ),
    ]
