# Generated by Django 5.0 on 2023-12-23 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_bill', '0005_rename_owes_debt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='ratio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
