# Generated by Django 5.0 on 2024-01-01 16:50

import django.core.validators
from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Debt = apps.get_model('splitit_bill', 'Debt')

    for debt in Debt.objects.all():
        ratio = debt.ratio

        if ratio == 0 or ratio == 100:
            ratio = 1
        else:
            ratio = (100 - debt.ratio) / 100
        debt.lent = debt.amount * ratio
        debt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_bill', '0007_alter_debt_is_owed_alter_debt_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='lent',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
    ]
