version: "3.1"

services:
  postgresql:
    image: postgres:16.1-bookworm
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
     - "5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/splitit-pgdata:/var/lib/postgresql/data:rw

  django:
    image: dtasev/splitit-backend:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    expose:
      - "8001"
    volumes:
      - ./backend/app:/app:rw
      - django_staticfiles:/data/django/staticfiles
    depends_on:
      - postgresql

  react:
    image: dtasev/splitit:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "5173"
    volumes:
      - ./app:/app:rw
    depends_on:
      - django

  nginx:
    image: dtasev/splitit-nginx:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "5555"
    ports:
      - "5555:5555"
    volumes:
      - django_staticfiles:/data/django/staticfiles
      - ./nginx/local-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - react

volumes:
  django_staticfiles:
    driver: local