version: "3.1"

services:
  postgresql:
    image: postgres:16.1-bookworm
    restart: always
    expose:
     - "5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=bzr6t2dd2g775c8oyibz
    volumes:
      - ~/splitit-pgdata:/var/lib/postgresql/data:rw
    container_name: splitit-psql

  django:
    image: dtasev/splitit-backend:latest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./backend/app:/app:rw
      - django_staticfiles:/data/django/staticfiles
    container_name: splitit-backend
    depends_on:
      - postgresql

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/dimitar/certbot/www/:/var/www/certbot/:rw
      - /home/dimitar/certbot/conf/:/etc/letsencrypt/:rw
    command: renew

  nginx:
    image: dtasev/splitit-nginx:latest
    restart: always
    expose:
      - "5555"
    ports:
      - 443:5555
      - 80:5554
    volumes:
      - django_staticfiles:/data/django/staticfiles
      - /home/dimitar/splitit/app/dist:/application
      - /home/dimitar/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - django
    container_name: splitit-nginx

volumes:
  django_staticfiles:
    driver: local